export const PRODUCT_CREATE_REQUEST= "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS= "PRODUCT_CREATE_SUCCESS";


export const PRODUCT_GET_DATA_REQUEST= "PRODUCT_GET_DATA_REQUEST";
export const PRODUCT_GET_DATA_SUCCESS= "PRODUCT_GET_DATA_SUCCESS";